sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^5
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start