sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
install:
  - export PATH=./node_modules/.bin/:$PATH
  - npm install -g node-pre-gyp-github@1.3.1
  - npm i -g typescript
  - npm i -g jasmine
  - npm i -g jasmine-spec-reporter
  - npm i -g jasmine-ts
  - npm i -g nyc
  - npm i -g ts-node
  - npm i @types/jasmine
before_install:
  - npm i -g npm@^5
before_script:
  - npm prune
  - brew update
  - brew install nvm
  - export NVM_DIR=~/.nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success: 'npm run coveralls'